### ISSUE TITLE
Incompatible with Linux

### ISSUE THREAD

**Issue by Lockszmith-GH** [realslacker/BitwardenWrapper#1]
Just wanted to start by saying - This module is great.

I've tried using the module on PowerShell Core on Linux and when Importing the module I get:
> ```
> WARNING: No Bitwarden CLI found in your path, either specify $env:BITWARDEN_CLI_PATH or put bw.exe in your path. You can use Install-BitwardenCLI to install to C:\Windows\System32
> ```

I checked the code, and it's because you are looking for `bw.exe`, on non-Windows it will be just `bw` - interestingly, `bw` will also work on Windows, so you might want to change that.

Setting the `BITWARDEN_CLI_PATH` environment variable to `bw` I get a different message:
> ```
> WARNING: Your Bitwarden CLI is version 0.0.0.0 and out of date, please upgrade to at least version 1.16.
> ```

This is because the FileVersion property is something that is populated only in Windows, so when not running in Windows one possible option would be to run `bw --version` to get the version, another is to test this at a later time, instead of during module-load.

Below is some output from my Ubuntu environment:
```
> Get-Command -Name bw | Format-List *

Name            : bw
CommandType     : Application
Definition      : /usr/local/bin/bw
Extension       : 
Path            : /usr/local/bin/bw
FileVersionInfo : File:             /usr/local/bin/bw
                  InternalName:     
                  OriginalFilename: 
                  FileVersion:      
                  FileDescription:  
                  Product:          
                  ProductVersion:   
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:         
                  

> bw --version
1.20.0
```

Hope you find this feedback helpful.

**Comment by undecomposed** [comment]
I will add this is not compatible with macOS either 😀

**Comment by realslacker** [comment]
I missed the version bit, I will look at this.
