### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by undecomposed** [realslacker/BitwardenWrapper#2]
This module currently does not recognize bwcli installed on macOS and PowerShell Core.

**Comment by undecomposed** [comment]
@realslacker I added a bit of code to allow it to recognize bwcli installation on macOS as well, however, I don’t think I can create a branch for you to review it. Is there a better way for me to share this with you?

**Comment by realslacker** [comment]
I have changed the module to look for "bw" instead of "bw.exe", I think this should be sufficient. Please give the new version a try and let me know.
